apiVersion: batch/v1
kind: Job
metadata:
  name: it-test
spec:
  ttlSecondsAfterFinished: 100
  template:
    spec:
      containers:
        - name: it-test
          image: localhost:5001/it-test:ci
          env:
            - name: URL
              value: http://kubegraph:3000
      restartPolicy: Never
  backoffLimit: 0
