name: Continuous integration

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main 

env:
  IMAGE_NAME: kubegraph
  K6_VERSION: "v0.39.0"

jobs:
  integration-test: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.3.0
      with: 
        cluster_name: kind
        config: it_test/kind-conf.yaml

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: Dockerfile
        push: false
        tags: ${{ env.IMAGE_NAME }}:test

    - name: Load and apply manifest
      run: |
        kind load docker-image ${{ env.IMAGE_NAME }}:test --name kind
        kubectl apply -f it_test/kube-ci.yaml
        sleep 5

    - name: Run integration test 
      run: |
        pip install -r requirements.txt
        pytest
      working-directory: it_test/pytest

  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: [integration-test]

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Build & Push Docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: Dockerfile
        push: true
        tags: |
          ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE_NAME }}:latest,
          ghcr.io/${{ github.repository_owner }}/spm-${{ env.IMAGE_NAME }}:main

