name: Continuous integration

on:
  push:
    branches: 
    - main
  pull_request:
    branches:
    - main 

env:
  IMAGE_NAME: kubegraph

jobs:
  integration-test: 
    runs-on: ubuntu-latest
    steps:
    - name: Create k8s Kind Cluster
      uses: helm/kind-action@v1.3.0

    - uses: actions/checkout@v3

    - name: Build Docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: Dockerfile
        push: false
        tags: ${IMAGE_NAME}:test

    - name: Load and apply manifest
      run: |
        kind load docker-image ${env.IMAGE_NAME}:test
        kubectl apply -f manifests/deploy.yaml

  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    needs: [integration-test]

    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    
    steps:
    - uses: actions/checkout@v3

    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin

    - name: Build & Push Docker image
      uses: docker/build-push-action@v2
      with: 
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/spm-${env.IMAGE_NAME}:${env.IMAGE_NAME}